name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch submodules
        run: |
          git submodule update --init components/int-mqtt/esp-mqtt
      - name: "Building project"
        uses: nsfilho/esp8266-rtos-sdk@v2
        with:
          makearg: "allcerts defconfig all size-components"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Generate Public Artifacts
        run: |
          mkdir public
          cp build/e12aio3.bin public
          cp build/ota_data_initial.bin public
          cp build/partitions.bin public
          cp build/phy_init_data.bin public
          cp tools/spiffs.bin public
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Upload e12aio3.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/e12aio3.bin
          asset_name: e12aio3.bin
          asset_content_type: application/octet-stream
      - name: Upload ota_data_initial.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ota_data_initial.bin
          asset_name: ota_data_initial.bin
          asset_content_type: application/octet-stream
      - name: Upload partitions.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/partitions.bin
          asset_name: partitions.bin
          asset_content_type: application/octet-stream
      - name: Upload phy_init_data.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/phy_init_data.bin
          asset_name: phy_init_data.bin
          asset_content_type: application/octet-stream
      - name: Upload spiffs.bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tools/spiffs.bin
          asset_name: spiffs.bin
          asset_content_type: application/octet-stream
